# These are supported funding model platforms

github: # [ANDIPANDI111, ANDREAMARIADB, 777NINJAMUSIC, ANDREA-MARIADB-2]
patreon # ANDREAMARIADB
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # ['https://datatracker.ietf.org/doc/html/draft-bradner-key-words-02, https://www.youtube.com/channel/UCuoDzKdqTwXtJe5kwo4tNYQ, https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg
.npm
